"""Token Parser Module.

Parses the raw formatted text output generated by the compiled FLEX lexer
into structured Token objects, identifying valid lexical tokens and errors.
"""

from dataclasses import dataclass, field
from typing import List, Set


VALID_TOKEN_TYPES: Set[str] = {
    "IDENTIFIER",
    "INTEGER",
    "FLOAT",
    "PLUS",
    "MINUS",
    "MULTIPLY",
    "DIVIDE",
    "MODULO",
    "POWER",
    "LPAREN",
    "RPAREN",
    "ASSIGN",
}

ERROR_MARKER = "ERROR: invalid character"


@dataclass
class Token:
    """Represents a single lexical token or error produced by the FLEX lexer."""
    index: int
    lexeme: str
    token_type: str
    is_error: bool = False
    error_message: str = ""


@dataclass
class TokenParseResult:
    """Collection of parsed tokens, separated into valid tokens and errors."""
    tokens: List[Token] = field(default_factory=list)
    valid_tokens: List[Token] = field(default_factory=list)
    errors: List[Token] = field(default_factory=list)

    @property
    def total_count(self) -> int:
        return len(self.tokens)

    @property
    def valid_count(self) -> int:
        return len(self.valid_tokens)

    @property
    def error_count(self) -> int:
        return len(self.errors)


def parse_lexer_output(raw_output: str) -> TokenParseResult:
    """Parse raw stdout from lexer.exe into structured Token instances.

    Each line produced by the FLEX rules is formatted as:
        %-15s <TOKEN_TYPE>
    or:
        %-15s ERROR: invalid character

    Args:
        raw_output: Raw string output from lexer.exe.

    Returns:
        TokenParseResult containing all tokens, valid tokens, and error tokens.
    """
    result = TokenParseResult()
    lines = raw_output.splitlines()
    token_index = 1

    for line in lines:
        stripped = line.strip()
        if not stripped:
            continue

        # Check for error lines produced by the FLEX '.' rule:
        # printf("%-15s ERROR: invalid character\n", yytext);
        if ERROR_MARKER in line:
            error_pos = line.find(ERROR_MARKER)
            lexeme = line[:error_pos].strip()
            if not lexeme and line:
                # In rare cases of whitespace/special char
                lexeme = line.replace(ERROR_MARKER, "").strip()

            token = Token(
                index=token_index,
                lexeme=lexeme,
                token_type="ERROR",
                is_error=True,
                error_message="Invalid character",
            )
            result.tokens.append(token)
            result.errors.append(token)
            token_index += 1
            continue

        # Standard token parsing: line ends with token type
        parts = stripped.rsplit(None, 1)
        if len(parts) == 2:
            lexeme, token_type = parts
            if token_type in VALID_TOKEN_TYPES:
                token = Token(
                    index=token_index,
                    lexeme=lexeme,
                    token_type=token_type,
                    is_error=False,
                    error_message="",
                )
                result.tokens.append(token)
                result.valid_tokens.append(token)
                token_index += 1
            else:
                # Unrecognized token type fallback
                token = Token(
                    index=token_index,
                    lexeme=lexeme,
                    token_type=token_type,
                    is_error=False,
                    error_message="",
                )
                result.tokens.append(token)
                result.valid_tokens.append(token)
                token_index += 1
        elif len(parts) == 1:
            # Single token string fallback
            token = Token(
                index=token_index,
                lexeme=parts[0],
                token_type="UNKNOWN",
                is_error=True,
                error_message="Unrecognized token format",
            )
            result.tokens.append(token)
            result.errors.append(token)
            token_index += 1

    return result
